Added board,player_control, and tests to Piece
ianm24/open_modular_chess pull request #13
Opened 2023-10-13 04:13 UTC by ianm24

2023-10-13 05:19 UTC, ianm24 commented
Closes #10

2023-10-16 03:04 UTC, jesp1999 requested changes
A few change requests

2023-10-16 03:04 UTC, jesp1999 commented on tests/unit/test_piece.py
> +    assert p.perform_action("move", ["t", "1"]) is False and p.perform_action(
Might be worth breaking these up into multiple statements for readability:
```
assert p.perform_action("move", ["t", "1"]) is False
assert p.perform_action("move", ["1", "t") is False
assert p.current_coords == (0,0)
```

2023-10-16 03:04 UTC, jesp1999 commented on tests/unit/test_piece.py
> +    p = Piece('t', 1, Board.empty(), player_controller=2)
Btw you can do `@pytest.mark.skip(reason=REASON)` to skip running a test or `@pytest.mark.xfail(reason=REASON)` to run the test but expect it to fail (if it succeeds it'll be marked like a failure, if it fails it'll be effectively ignored)

2023-10-16 04:04 UTC, jesp1999 approved these changes

2023-10-16 04:04 UTC, merged